---
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    env_file:
      - .env
  ollama:
    image: ollama/ollama
    container_name: ollama
    hostname: ollama
    restart: always
    build:
      dockerfile: ./services/ollama/Dockerfile
    ports:
      - 11434:11434

  data_acquisition:
    build:
      context: .
      dockerfile: ./services/data_acquisition/Dockerfile
    container_name: data_acquisition
    depends_on:
      - rabbitmq
    env_file:
      - services/data_acquisition/.env
  summary_llm:
    build:
      context: .
      dockerfile: ./services/summary_of_content_changes/Dockerfile
    container_name: summary_of_content_changes
    depends_on:
      - rabbitmq
      - ollama
    env_file:
      - services/summary_of_content_changes/.env
      
  data_management:
    build:
      context: .
      dockerfile: ./services/data_management/Dockerfile
    container_name: data_management
    depends_on:
      - rabbitmq
    ports:
      - 5000:5000

  versioning_and_change_tracking:
    build:
      context: .
      dockerfile: ./services/versioning_and_change_tracking/Dockerfile
    container_name: versioning_and_change_tracking
    volumes:
      - ./services/versioning_and_change_tracking/sample.json:/app/sample.json
    depends_on:
      - rabbitmq
    env_file:
      - services/versioning_and_change_tracking/.env
