name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker images
      run: |
        for module in services/*/; do
          if [ -f "$module/Dockerfile" ]; then 
            service_name=$(basename "$module")
            echo "Building image for $service_name"
            docker build "$module" --file "$module/Dockerfile" --tag "my-image-$service_name:$(date +%s)"
          else
            echo "Skipping $module (no Dockerfile found)"
          fi
        done
