name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        for module in $(ls -d services/*/); do
          if [ -f "$moduleDockerfile"]; then
            service_name=$(basename "$module")
            echo "Building image for $service_name"
            docker build "$module" --file "$moduleDockerfile" --tag "my-image-$service_name:$(date +%s)"
          else
            echo "Skipping $module (no Dockerfile found)"
          fi
        done
